on:
  issue_comment:
    types: [created]
name: Pull messages
jobs:
  merge:
    name: Pull messages
    if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/pull-messages')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lokalise Pull Messages
        uses: igorDolzh/localise-pull-messages@v0.0.9
        with:
          # Api token for the Lokalise account
          # with read/write access to the project
          api-token: ${{ secrets.LOCALIZE_TOKEN }}

          # ID of the project to sync
          project-id: ${{ secrets.LOCALIZE_PROJECT }}

          # The relative file path where language files will be found
          file-path: src/locales/%LANG_ISO%/messages.po

          download-options: '{"export_empty_as": "skip", "format": "po"}'
      - name: Commiting messages
        env:
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}
        run: |
          git config --global user.email "dev@pleo.io"
          git config --global user.name "Dev bot"
          git add .
          git commit -m "Merge with master: message extraction"
          git push
